### ISSUE TITLE
multi-file support clarification 

### ISSUE THREAD

**Issue by waalge** [dcSpark/cddl-codegen#157]
I think some docs are out of sync: 

- https://github.com/dcSpark/cddl-codegen/blob/f0975bb34e36c0deaab5e7a4e21ea34e37988be3/README.md?plain=1#L78
- https://github.com/dcSpark/cddl-codegen/blob/f0975bb34e36c0deaab5e7a4e21ea34e37988be3/GENERATING_SERIALIZATION_LIB.md?plain=1#L10

... It's supported now, right?

**Comment by rooooooooob** [comment]
the README has been updated with #147 to mention multi-file support

I didn't touch that `GENERATING_SERIALIZATION_LIB.md` file, but that is super out of date. It's only relevant for when we used this at Emurgo to generate CSL. I'm not sure if we should just remove that file altogether or put a note at the top saying it's not necessarily up to date.
