### ISSUE TITLE
serilization.rs missing

### ISSUE THREAD

**Issue by evenl** [dcSpark/cddl-codegen#212]
When I try to generate an serialization interface with cddl-codegen it will generate lib.rs in rust/src, but then it will fail with the message "can't read: .static/serialization.rs". I have attached to log from the output

This is how I ran the code:
cddl-codegen --input ../../../ncs/nrf/samples/multicore/ram_application_spi/cddl/* --output ../../common/src/ --lib-name cddl 

the backtrace environment variable was set like this RUST_BACKTRACE=full

The output:
[log.txt](https://github.com/dcSpark/cddl-codegen/files/13248241/log.txt)

The input (added .log as github do not accept files with .cddl extension):
[flash_proto.cddl.log](https://github.com/dcSpark/cddl-codegen/files/13248283/flash_proto.cddl.log)

I used zcbor to generate C code from the same file without any problem, and the C code looks fine.

Tested version: 9661c92a7e6d970f88bfdc8e04d38def367a2e77

**Comment by evenl** [comment]
Seems to be similar to #201

**Comment by rooooooooob** [comment]
@evenl  If you don't run it from the root directory you'll have to pass in `--static-dir=<path to the files in /static/>`. [these](https://github.com/dcSpark/cddl-codegen/tree/master/static)

**Comment by rooooooooob** [comment]
Closing under the assumption that it was not being run from the directory where the `/static/` files were and the command did not specify one and it's been a month without clarification. Feel free to reopen it if that was not the case.
