### ISSUE TITLE
Add f32 & f64 to prelude

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/cddl-codegen#75]
Not sure about floating point spec in CBOR vs floating point implementation in Rust. Additionally, I'm not sure if we support float types at all in the first place such as in `FixedValue` (and I would recommend against using them)

**Comment by rooooooooob** [comment]
`cbor_event` (which the generated code uses) doesn't support floats

**Comment by SebastienGllmt** [comment]
See #129
